### ISSUE TITLE
Running build process fails

### ISSUE THREAD

**Issue by chbndrhnns** [FriendlyUser/vuepress-theme-cool-starter#1]
While I can run the dev server fine after cloning the repo, I see a failing build using `node ./node_modules/vuepress/bin/vuepress.js build docs/`

```
➜  vuepress-theme-cool-starter git:(master) ✗ node ./node_modules/vuepress/bin/vuepress.js build docs/

 WAIT  Extracting site metadata...
<badge class="warning">warning </badge>
<span class="badge badge-default">New</span>
<span class="badge error">ERROR</span>
[6:25:24 PM] Compiling Client
[6:25:24 PM] Compiling Server
(node:57169) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[6:25:33 PM] Compiled Server in 9s
[6:25:41 PM] Compiled Client in 17s
 WAIT  Rendering static HTML...
Rendering page: / FAIL  Error rendering /:
ReferenceError: document is not defined
    at Object.<anonymous> (/Users/powerjo/dev/scratch/vuepress-theme-cool-starter/node_modules/vue-good-table/dist/vue-good-table.cjs.js:2300:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at r (/Users/powerjo/dev/scratch/vuepress-theme-cool-starter/node_modules/vue-server-renderer/build.js:8335:16)
    at Object.<anonymous> (webpack:/external "vue-good-table":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (server-bundle.js:24575:32)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (server-bundle.js:37739:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at server-bundle.js:118:18
```

Could you help me with that error, please?

**Comment by FriendlyUser** [comment]
A quick google search indicates https://github.com/vuejs/vuepress/issues/442 may be related to what you are looking for.

I didn't get the build errors when I started from a fresh repo. 

Node v.10.14.1 Windows 10.

The issue doesn't seem to be platform specific. Could you tell me what version of node you are using and what operating system?

I updated the build pipeline and the problem doesn't seem to be platform specific, https://travis-ci.org/FriendlyUser/vuepress-theme-cool-starter/builds/496870617. 

![image](https://user-images.githubusercontent.com/13860264/53221754-af090200-361f-11e9-99a8-994f164bea50.png)

If you are starting with the latest repo, I would need to see your configuration files.  The reason windows is not included in the build process is because it is windows.

**Comment by chbndrhnns** [comment]
I found that the Vue-good-table might be the cause for the trouble. You use version 2.8 and I was somehow not careful with the dependencies and 2.16 was installed. This breaks the build process for me. 
Fixing the version to ~2.8.2 worked here.
